### ISSUE TITLE
Missing Modules: RL  Required for Running S3 and generate.batch

### ISSUE THREAD

**Issue by winnie-vq** [ZJU-DAILY/S3#3]
非常感谢您开发并分享了这个项目，它对我的研究提供了很大的帮助。
        在尝试运行 S3 模块时，我遇到了一些问题。项目中缺少了 `RL` 和 `generate.batch` 这两个模块，这导致我无法成功运行 S3.py。例如在utils文件中的dad_op函数需要RL中的angle内容，这对项目的正确运行是至关重要的。
        具体而言，当我运行以下命令时：
        python models/s3.py --config ./model_configs/camera/s3.yaml
        我遇到了这样的错误提示：
        - `ModuleNotFoundError: No module named 'RL'`
        - 在其他文件中，也提示缺少 `generate.batch` 模块。
       我在项目中搜索了这些模块，但没有找到。请问是否是在上传项目到 GitHub 时遗漏了这部分内容。请问您能否帮助提供这些缺失的模块，期待您的回复，祝好。

**Comment by AlecHenx** [comment]
I've updated code in commit 160288f7636ce74fe651db8f88d0482acedb490a.

There are two problems:

1.The loss of RL module, RL is our baseline, so I reference some code of them. Now, I add the `angle` code in "generate/utils", RL baseline is at https://github.com/zhengwang125/RLTS. It may be helpful to you. 

2.The loss of generate.batch module. This module onws some baselines and is none of bussiness with training model, so you can delete code which is related to generate.batch. And the code of comparision method is at https://github.com/uestc-db/traj-compression, maybe you'll use them.
