### ISSUE TITLE
Evaluate metric problem and some preprocess problem

### ISSUE THREAD

**Issue by LowderR** [ZJU-DAILY/S3#4]
Thank you very much for developing this program, but I'm having some problems running it, and I hope you have the time to answer them:
1. When I set gnn_used to true in the config file, I need a gid2poi.txt, how should I get this file?
2. When I get the compressed trajectory from debug_outputs.py, how should I evaluate the compressed metric since it is a sequence of grid points and not exact gps points?

**Comment by AlecHenx** [comment]
1. Check `preprocess/POI.py`, then you will find the way to generate gid2pot.txt.

2. We perceive the trajectory GPS point as a grid point; however, if you wish to convert the grid point back into a GPS point, you can calculate the center point of the grid as the GPS point, which will inevitably introduce errors.

Feel free to contact us with email:` alecs2775@gmail.com`
